apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  labels:
    app: nodejs-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nodejs-app
    version: blue  # Initially pointing to blue
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-blue-service
  labels:
    app: nodejs-app
    version: blue
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nodejs-app
    version: blue
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-green-service
  labels:
    app: nodejs-app
    version: green
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nodejs-app
    version: green
